### PR TITLE
Profiler tooling has been moved out to `performance_vizualisation` repo

### PR DESCRIPTION
**Pull request by FlorianDeconinck**
## Purpose

`nsys` and `reproducer` tooling have been moved out to `performance_vizualisation` repository to clean up `fv3core` and allow for other repository to be profiled with it.

## Code changes:

Removing everything under `/profiler`

## Checklist

- [x] You have followed the coding standards guidelines established at [Code Review Checklist](https://paper.dropbox.com/doc/Code-Review-Checklist--BD7zigBMAhMZAPkeNENeuU2UAg-IlsYffZgTwyKEylty7NhY).
- [x] Docstrings and type hints are added to new and updated routines, as appropriate
- [x] All relevant documentation has been updated or added (e.g. README, CONTRIBUTING docs)
- [x] Unit tests are added or updated for non-stencil code changes

### CODE REVIEW

**Review by eddie-c-davis — APPROVED** [review]
-2,208 lines, nice. LGTM!

**Comment by ofuhrer** [comment]
Can one of the admins verify this patch?

**Comment by twicki** [comment]
ok to test

**Comment by FlorianDeconinck** [comment]
launch jenkins

**Pull request merged**
